// Autogenerated by Nightwatch
// Refer to the online docs for more details: https://nightwatchjs.org/gettingstarted/configuration/
const Services = {};
loadServices();

module.exports = {
  src_folders: ['nightwatch'],

  webdriver: {
    start_process: true,
    server_path: 'node_modules/.bin/chromedriver',
    cli_args: ['--verbose'],
    port: 9000,
    keep_alive: { enabled: true, keepAliveMsecs: 2000 },
  },

  test_settings: {
    default: {
      globals: {
        user: 'tweets@webrooster.ch',
        pw: '_Tweets_3ster',
      },
      desiredCapabilities: {
        browserName: 'chrome',
      },
    },
  },
};

function loadServices() {
  try {
    Services.seleniumServer = require('selenium-server');
  } catch (err) {}

  try {
    Services.chromedriver = require('chromedriver');
  } catch (err) {}

  try {
    Services.geckodriver = require('geckodriver');
  } catch (err) {}
}
